[project]
name = "ai-research-report-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "anonymous298", email = "tackletalha@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "anthropic>=1.9.0",
    "asyncio>=4.0.0",
    "fastapi>=0.142.0",
    "gradio>=6.29.0",
    "httpx>=0.28.1",
    "jupyter>=1.1.1",
    "langchain>=1.4.3",
    "langgraph>=1.2.12",
    "numpy>=2.5.3",
    "openai>=3.22.0",
    "openai-agents>=0.22.3",
    "pandas>=3.0.6",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "seaborn>=0.13.2",
    "streamlit>=1.64.0",
]
